name: NPM Audit Endpoint Test-1

on:
  workflow_dispatch:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read



jobs:

  npm-audit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: Configure npm registry
        env:
         IDENTIFIER: "gha:${{ github.repository }}/${{ github.run_id }}/${{ job.check_run_id }}"
         NPM_TOKEN: ${{ secrets.STEPSECURITY_NPM_TOKEN }}
        run: |
             npm config set registry https://registry.stepsecurity.io/javascript
             npm config set //registry.stepsecurity.io/javascript/:_authToken "${NPM_TOKEN}::${IDENTIFIER}"

      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"

      - name: Show versions
        run: |
          node --version
          npm --version

      - name: Show configured registry
        run: npm config get registry

      - name: Install dependencies
        run: npm ci --ignore-scripts --audit=false

      - name: Run NPM Audit
        run: npm audit --json
        continue-on-error: true
